# Development Configuration
app:
  name: "Go API Server - DEV"
  version: "1.0.0"
  env: "development"
  debug: true

server:
  host: "localhost"
  port: 8080
  read_timeout: "30s"
  write_timeout: "30s"
  idle_timeout: "60s"

database:
  driver: "sqlite3"
  host: ""
  port: 0
  user: "test_user"
  password: "test_user_password"
  dbname: "dev.db"
  sslmode: "disable"
  max_open_conns: 5
  max_idle_conns: 2
  conn_max_lifetime: "30m"

# redis:
#   host: "localhost"
#   port: 6379
#   password: ""
#   db: 0
#   pool_size: 5

# jwt:
#   secret: "dev-jwt-secret-key-change-in-prod"
#   expiry: "24h"
#   refresh_expiry: "168h"

# logging:
#   level: "debug"
#   format: "text"
#   output: "stdout"

cors:
  allowed_origins:
    - "http://localhost:3000"
    - "http://localhost:3001"
    - "http://127.0.0.1:3000"
  allowed_methods:
    - "GET"
    - "POST"
    - "PUT"
    - "DELETE"
    - "OPTIONS"
    - "PATCH"
  allowed_headers:
    - "*"

# email:
#   smtp_host: "localhost"
#   smtp_port: 1025
#   username: ""
#   password: ""
#   from: "dev@localhost.com"

# storage:
#   type: "local"
#   local_path: "./dev-uploads"
#   max_file_size: "50MB"

rate_limit:
  enabled: false
  requests_per_minute: 1000
  burst: 100

pagination:
  default_page_size: 10
  max_page_size: 50