# Default Configuration (Base)
app:
  name: "Go API Server"
  version: "1.0.0"
  env: "local"
  debug: true

server:
  host: "localhost"
  port: 8080
  read_timeout: "30s"
  write_timeout: "30s"
  idle_timeout: "60s"

database:
  driver: "sqlite3"
  host: ""
  port: 0
  user: ""
  password: ""
  dbname: "app.db"
  sslmode: "disable"
  max_open_conns: 10
  max_idle_conns: 5
  conn_max_lifetime: "1h"

# redis:
#   host: "localhost"
#   port: 6379
#   password: ""
#   db: 0
#   pool_size: 10

# jwt:
#   secret: "default-secret-key"
#   expiry: "24h"
#   refresh_expiry: "168h"

# logging:
#   level: "info"
#   format: "text"
#   output: "stdout"

cors:
  allowed_origins:
    - "http://localhost:3000"
  allowed_methods:
    - "GET"
    - "POST"
    - "PUT"
    - "DELETE"
    - "OPTIONS"
  allowed_headers:
    - "Authorization"
    - "Content-Type"

# email:
#   smtp_host: "localhost"
#   smtp_port: 587
#   username: ""
#   password: ""
#   from: "noreply@localhost.com"

# storage:
#   type: "local"
#   local_path: "./uploads"
#   max_file_size: "10MB"

rate_limit:
  enabled: false
  requests_per_minute: 60
  burst: 10

pagination:
  default_page_size: 20
  max_page_size: 100